winzou_state_machine:
    sylius_refund_refund_payment:
        class: Sylius\RefundPlugin\Entity\RefundPayment
        transitions:
            # Special case for automated refunds
            confirm:
                from: [new]
                to: completed
        callbacks:
            after:
                process_refund_payment:
                    on: ["confirm"]
                    do: ["@sylius_adyen.processor.refund.refund_payment_state", "process"]
                    args: ["object"]
                    priority: 100
                resolve_order_payment_state:
                    on: ["complete", "confirm"]
                    do: ["@sylius_adyen.refund.state_resolver.order_fully_refunded", "resolve"]
                    args: ["object.getOrder().getNumber()"]
